[package]
name = "app"
version = "1.0.0"
authors = ["Alain Brenzikofer"]
build = "build.rs"

[dependencies]
sgx_types = "1.0.5"
sgx_urts = "1.0.5"
dirs = "1.0.2"
ipfs-api = "0.5.0-alpha2"
futures = "0.1"
hyper = "0.12"